# Generated by Django 5.1 on 2026-04-29 17:26

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('source', models.CharField(choices=[('website_form', 'Website Form'), ('upwork', 'Upwork'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('cold_outreach', 'Cold Outreach'), ('networking', 'Networking'), ('other', 'Other')], db_index=True, max_length=50)),
                ('source_detail', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiating', 'Negotiating'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('nurture', 'Nurture'), ('disqualified', 'Disqualified')], db_index=True, default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('probability', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('retail', 'Retail'), ('real_estate', 'Real Estate'), ('manufacturing', 'Manufacturing'), ('media', 'Media'), ('consulting', 'Consulting'), ('other', 'Other')], max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('last_contact_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_hot', models.BooleanField(db_index=True, default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('note_added', 'Note Added'), ('email_sent', 'Email Sent'), ('call_made', 'Call Made'), ('meeting_scheduled', 'Meeting Scheduled'), ('proposal_sent', 'Proposal Sent'), ('proposal_viewed', 'Proposal Viewed'), ('status_changed', 'Status Changed'), ('follow_up_set', 'Follow-up Set'), ('task_completed', 'Task Completed'), ('imported', 'Imported'), ('ai_generated', 'AI Generated'), ('email_opened', 'Email Opened'), ('link_clicked', 'Link Clicked'), ('website_visit', 'Website Visit'), ('form_submitted', 'Form Submitted')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('converted', 'Converted'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'lead_proposals',
            },
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_website_visits', models.IntegerField(default=0)),
                ('total_pages_viewed', models.IntegerField(default=0)),
                ('total_time_on_site_seconds', models.IntegerField(default=0)),
                ('email_opens_count', models.IntegerField(default=0)),
                ('email_clicks_count', models.IntegerField(default=0)),
                ('proposal_views_count', models.IntegerField(default=0)),
                ('proposal_time_spent_seconds', models.IntegerField(default=0)),
                ('form_submissions_count', models.IntegerField(default=0)),
                ('calls_scheduled_count', models.IntegerField(default=0)),
                ('meetings_attended_count', models.IntegerField(default=0)),
            ],
        ),
    ]
