# Generated by Django 5.1 on 2026-04-29 18:39

import django.core.validators
import django.utils.timezone
import leads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadscore',
            name='content_downloads_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadscore',
            name='demographic_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='depth_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='engagement_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='first_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='frequency_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='intent_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='last_calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='last_email_open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='last_proposal_view_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='next_calculation_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='previous_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='recency_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='score_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='score_history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='score_tier',
            field=models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('qualified', 'Qualified')], db_index=True, default='cold', max_length=20),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='scoring_weights',
            field=models.JSONField(default=leads.models.default_scoring_weights),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='social_interactions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='total_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='leadscore',
            index=models.Index(fields=['user', 'total_score'], name='score_user_total_idx'),
        ),
        migrations.AddIndex(
            model_name='leadscore',
            index=models.Index(fields=['score_tier', 'total_score'], name='score_tier_total_idx'),
        ),
        migrations.AlterModelTable(
            name='leadscore',
            table='lead_scores',
        ),
    ]
