# Generated by Django 5.1 on 2026-04-29 17:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latency_ms', models.IntegerField()),
                ('prompt_template_used', models.CharField(blank=True, max_length=255)),
                ('was_cached', models.BooleanField(default=False)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
