# Generated by Django 5.1 on 2026-05-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
        ('proposals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='completion_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='cost_usd',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='latency_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='proposals.proposal'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
