# Generated by Django 5.1 on 2026-04-29 17:59

import dashboard.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('total_leads', 'Total Leads'), ('conversion_rate', 'Conversion Rate'), ('pipeline_value', 'Pipeline Value'), ('recent_activity', 'Recent Activity'), ('proposals_generated', 'Proposals Generated'), ('proposals_accepted', 'Proposals Accepted'), ('lead_score_distribution', 'Lead Score Distribution'), ('lead_source_breakdown', 'Lead Source Breakdown'), ('monthly_revenue', 'Monthly Revenue'), ('follow_up_reminders', 'Follow-up Reminders'), ('ai_usage_stats', 'AI Usage Stats'), ('top_performing_templates', 'Top Templates')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('position', models.JSONField(default=dashboard.models.default_widget_position)),
                ('config', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('refresh_interval_seconds', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['id'],
            },
        ),
    ]
