# Generated by Django 5.1 on 2026-04-29 17:26

import django.contrib.postgres.fields
import django.contrib.postgres.search
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_company', models.CharField(blank=True, max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('job_description', models.TextField()),
                ('job_url', models.URLField(blank=True)),
                ('job_platform', models.CharField(blank=True, choices=[('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('fiverr', 'Fiverr'), ('linkedin', 'LinkedIn'), ('direct', 'Direct'), ('other', 'Other')], max_length=50)),
                ('generated_content', models.JSONField(default=dict)),
                ('final_content', models.TextField(blank=True)),
                ('tone_used', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('persuasive', 'Persuasive'), ('technical', 'Technical')], default='professional', max_length=20)),
                ('word_count', models.IntegerField(default=0)),
                ('ai_model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('ai_cost_usd', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('generation_time_ms', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('edited', 'Edited'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('custom_variables', models.JSONField(default=dict)),
                ('attachments', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('folder', models.CharField(choices=[('inbox', 'Inbox'), ('templates', 'Templates'), ('sent', 'Sent'), ('archived', 'Archived')], db_index=True, default='inbox', max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_app', 'Mobile App'), ('design', 'Design'), ('marketing', 'Marketing'), ('writing', 'Writing'), ('consulting', 'Consulting'), ('other', 'Other')], db_index=True, max_length=50)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('persuasive', 'Persuasive'), ('technical', 'Technical')], default='professional', max_length=20)),
                ('structure', models.JSONField(default=dict)),
                ('default_variables', models.JSONField(default=dict)),
                ('is_favorite', models.BooleanField(db_index=True, default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('is_system_template', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'proposal_templates',
                'ordering': ['-is_favorite', '-usage_count', '-created_at'],
            },
        ),
    ]
