# Generated by Django 5.1 on 2026-04-29 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposaltemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='proposals.proposaltemplate'),
        ),
        migrations.AddIndex(
            model_name='proposaltemplate',
            index=models.Index(fields=['user', 'category', 'is_active'], name='template_user_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='proposaltemplate',
            index=models.Index(fields=['is_system_template', 'is_public', 'is_active'], name='template_system_public_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposaltemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'name'), name='unique_template_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['user', 'status', 'is_active'], name='proposal_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['user', 'folder', 'is_active'], name='proposal_user_folder_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['client_email', 'is_active'], name='proposal_client_email_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['job_platform', 'is_active'], name='proposal_platform_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='valid_rating_range'),
        ),
    ]
